baseURL = "https://fermedegouet.fr/"
languageCode = "fr-fr"
title = "Ferme de Gouet"
staticDir = "dist/static"
publishDir = "dist/public"
DefaultContentLanguage = "fr"

[params]
email = "contact@fermedegouet.fr"
phone = "+33 6 46 43 72 89"
address = [ "Ferme de Gouet", "42220 La Versanne" ]
description = "Site de la Ferme de Gouet"
pretTotal = 130000
pretActuel = 55700
tauxMin = 0
tauxMax = 1.5
dateLimite = "2019-06-15"
longitude = 45.311703
latitude = 4.499096
crowdfundingURL = "https://api.fermedegouet.fr"
